[package]
name = "gx_report"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
gx_core = { path = "../gx_core" }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
directories = "5.0"
printpdf = { version = "0.12", default-features = false }
